# Generated by Django 4.2.5 on 2023-10-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecmp', '0005_alter_product_amazon_price_alter_product_croma_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/pricecmp/images/'),
        ),
    ]
