# Generated by Django 4.2.5 on 2023-10-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecmp', '0007_remove_product_croma_price_remove_product_croma_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Apple', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Mobiles', max_length=100),
            preserve_default=False,
        ),
    ]
