# Generated by Django 4.2.5 on 2023-10-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecmp', '0008_product_brand_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_price',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flipkart_price',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
